/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  PermissionsStorage,
  PermissionsStorageInterface,
} from "../../../@thirdweb/plugin/PermissionsStorage";

const _abi = [
  {
    inputs: [],
    name: "PERMISSIONS_STORAGE_POSITION",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a6610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80630998ed3b146038575b600080fd5b605e7fd0ebebe8e6445c62babf8fef767eb39f1002bb957bb5b83258275a4e46428ed581565b60405190815260200160405180910390f3fea2646970667358221220b51827bade6118e2a90cad85db63d0a1cf0167bfaee08f1b659d1533dd68f04d64736f6c63430008130033";

type PermissionsStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PermissionsStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PermissionsStorage__factory extends ContractFactory {
  constructor(...args: PermissionsStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<PermissionsStorage> {
    return super.deploy(overrides || {}) as Promise<PermissionsStorage>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): PermissionsStorage {
    return super.attach(address) as PermissionsStorage;
  }
  override connect(signer: Signer): PermissionsStorage__factory {
    return super.connect(signer) as PermissionsStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PermissionsStorageInterface {
    return new utils.Interface(_abi) as PermissionsStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PermissionsStorage {
    return new Contract(address, _abi, signerOrProvider) as PermissionsStorage;
  }
}
