/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  PermissionsEnumerableStorage,
  PermissionsEnumerableStorageInterface,
} from "../../../@thirdweb/plugin/PermissionsEnumerableStorage";

const _abi = [
  {
    inputs: [],
    name: "PERMISSIONS_ENUMERABLE_STORAGE_POSITION",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a6610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063871ef69d146038575b600080fd5b605e7f0c4ba382c0009cf238e4c1ca1a52f51c61e6248a70bdfb34e5ed49d5578a5c0c81565b60405190815260200160405180910390f3fea2646970667358221220289188da872f31f6767369df09a6f25ffd66919eefe1094ce1f62d5fd0b46eea64736f6c63430008130033";

type PermissionsEnumerableStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PermissionsEnumerableStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PermissionsEnumerableStorage__factory extends ContractFactory {
  constructor(...args: PermissionsEnumerableStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<PermissionsEnumerableStorage> {
    return super.deploy(
      overrides || {}
    ) as Promise<PermissionsEnumerableStorage>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): PermissionsEnumerableStorage {
    return super.attach(address) as PermissionsEnumerableStorage;
  }
  override connect(signer: Signer): PermissionsEnumerableStorage__factory {
    return super.connect(signer) as PermissionsEnumerableStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PermissionsEnumerableStorageInterface {
    return new utils.Interface(_abi) as PermissionsEnumerableStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PermissionsEnumerableStorage {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as PermissionsEnumerableStorage;
  }
}
