/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  ReentrancyGuardStorage,
  ReentrancyGuardStorageInterface,
} from "../../../@thirdweb/plugin/ReentrancyGuardStorage";

const _abi = [
  {
    inputs: [],
    name: "REENTRANCY_GUARD_STORAGE_POSITION",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a6610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063984b83ff146038575b600080fd5b605e7fbbf78d3411d42a81effd97bb8c69faae4e77e75cec462245c1001191a0634c6f81565b60405190815260200160405180910390f3fea2646970667358221220b05c9ab8aa9c1d3788554f4e22c5b85945b9770ebeaeba49d3a5f3f738a9072964736f6c63430008130033";

type ReentrancyGuardStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReentrancyGuardStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReentrancyGuardStorage__factory extends ContractFactory {
  constructor(...args: ReentrancyGuardStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ReentrancyGuardStorage> {
    return super.deploy(overrides || {}) as Promise<ReentrancyGuardStorage>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ReentrancyGuardStorage {
    return super.attach(address) as ReentrancyGuardStorage;
  }
  override connect(signer: Signer): ReentrancyGuardStorage__factory {
    return super.connect(signer) as ReentrancyGuardStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrancyGuardStorageInterface {
    return new utils.Interface(_abi) as ReentrancyGuardStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ReentrancyGuardStorage {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ReentrancyGuardStorage;
  }
}
