/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as common from "./common";
export type { common };
import type * as draftIerc1822Sol from "./draft-IERC1822.sol";
export type { draftIerc1822Sol };
export type { ERC165 } from "./ERC165";
export type { ERC20 } from "./ERC20";
export type { IERC1155 } from "./IERC1155";
export type { IERC165 } from "./IERC165";
export type { IERC20 } from "./IERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IERC20Permit } from "./IERC20Permit";
export type { IERC721 } from "./IERC721";
