/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC2981__factory } from "./ERC2981__factory";
export { IERC2981__factory } from "./IERC2981__factory";
