/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  EnglishAuctionsStorage,
  EnglishAuctionsStorageInterface,
} from "../../@thirdweb/EnglishAuctionsStorage";

const _abi = [
  {
    inputs: [],
    name: "ENGLISH_AUCTIONS_STORAGE_POSITION",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a6610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806385ec7cf6146038575b600080fd5b605e7fd526f5655f36f7dc8e8bd7b8ff16d8886b1e27059b0d19a6ab0f4742ac8dc6e381565b60405190815260200160405180910390f3fea2646970667358221220af672069129df23021374391c8be81ee675d0a5a9b6a625bcfa3570f17b47aa864736f6c63430008130033";

type EnglishAuctionsStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EnglishAuctionsStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EnglishAuctionsStorage__factory extends ContractFactory {
  constructor(...args: EnglishAuctionsStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<EnglishAuctionsStorage> {
    return super.deploy(overrides || {}) as Promise<EnglishAuctionsStorage>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): EnglishAuctionsStorage {
    return super.attach(address) as EnglishAuctionsStorage;
  }
  override connect(signer: Signer): EnglishAuctionsStorage__factory {
    return super.connect(signer) as EnglishAuctionsStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EnglishAuctionsStorageInterface {
    return new utils.Interface(_abi) as EnglishAuctionsStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EnglishAuctionsStorage {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as EnglishAuctionsStorage;
  }
}
