/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ERC2771ContextConsumer,
  ERC2771ContextConsumerInterface,
} from "../../../../@thirdweb/plugin/ERC2771ContextConsumer.sol/ERC2771ContextConsumer";

const _abi = [
  {
    inputs: [],
    name: "_msgData",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "_msgSender",
    outputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ERC2771ContextConsumer__factory {
  static readonly abi = _abi;
  static createInterface(): ERC2771ContextConsumerInterface {
    return new utils.Interface(_abi) as ERC2771ContextConsumerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC2771ContextConsumer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC2771ContextConsumer;
  }
}
